name: Release .app and .workflow folders

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

permissions:
  contents: write  # 确保 GITHUB_TOKEN 有写权限

jobs:
  release-apps-workflows:
    runs-on: macos-latest  # 使用 macOS 环境
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Find all .app and .workflow directories in the root folder
      - name: Find .app and .workflow directories
        id: find_folders
        run: |
          folders=$(find . -maxdepth 1 -type d \( -name "*.app" -o -name "*.workflow" \))
          echo "Found directories: $folders"

          # Create a JSON file with the list of .app and .workflow directories
          echo "[" > folders.json
          first=1
          for folder in $folders; do
            if [ $first -eq 1 ]; then
              first=0
            else
              echo "," >> folders.json
            fi
            echo "{\"path\": \"$folder\"}" >> folders.json
          done
          echo "]" >> folders.json
        shell: bash

      # Step 3: Read the JSON file and create a release for each folder
      - name: Create releases for .app and .workflow folders
        run: |
          count=$(jq length folders.json)
          for (( i=0; i<count; i++ )); do
            folder=$(jq -r ".[$i].path" folders.json)
            echo "Processing folder: $folder"
            
            # 获取当前时间作为版本号
            timestamp=$(date +%Y%m%d%H%M%S)
            folder_name=$(basename "$folder")

            # 打包文件夹为 ZIP 文件
            zip_file="${folder_name}_${timestamp}.zip"
            zip -r "$zip_file" "$folder"

            # 创建 GitHub Release
            release_response=$(curl --request POST \
              --url "https://api.github.com/repos/${{ github.repository }}/releases" \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              --header "Content-Type: application/json" \
              --data '{
                "tag_name": "'"$folder_name-$timestamp"'",
                "target_commitish": "'"${{ github.sha }}"'",
                "name": "'"$folder_name $timestamp"'",
                "draft": false,
                "prerelease": false
              }')

            # 获取最新创建的 Release ID
            release_id=$(echo "$release_response" | jq '.id')

            # 上传 ZIP 文件到 Release
            curl --request POST \
              --url "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=$zip_file" \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              --header "Content-Type: application/zip" \
              --upload-file "$zip_file"
          done
        shell: bash