name: Release .app and .workflow folders

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

permissions:
  contents: write  # 确保 GITHUB_TOKEN 有写权限

jobs:
  release-apps-workflows:
    runs-on: macos-latest  # 使用 macOS 环境
    steps:
      # Step 1: Checkout repository with full commit history (fetch at least 2 commits)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 拉取当前和上一个提交

      # Step 2: Find all changed .app and .workflow directories recursively
      - name: Find changed .app and .workflow directories
        id: find_changed_folders
        run: |
          # 检查是否有足够的历史提交
          if [ $(git rev-list --count HEAD) -lt 2 ]; then
            echo "Not enough commit history to compare. Exiting."
            echo "changed_folders=" >> $GITHUB_ENV
            exit 0
          fi

          # 获取当前提交与上一提交之间有变化的文件
          changed_files=$(git diff --name-only HEAD~1 HEAD)

          # 输出调试信息
          echo "Changed files detected:"
          echo "$changed_files"

          # 检查是否有变化的文件
          if [ -z "$changed_files" ]; then
            echo "No changes detected."
            echo "changed_folders=" >> $GITHUB_ENV
            exit 0
          fi

          # 递归查找 .app 和 .workflow 文件夹中有变动的文件
          changed_folders=$(echo "$changed_files" | grep -E '(^.+\.app/|^.+\.workflow/)' | cut -d '/' -f 1 | sort | uniq)

          # 输出过滤后的文件夹
          echo "Filtered changed folders:"
          echo "$changed_folders"

          # 如果没有相关的文件夹变化，则退出
          if [ -z "$changed_folders" ]; then
            echo "No .app or .workflow directories changed."
            echo "changed_folders=" >> $GITHUB_ENV
            exit 0
          fi

          # 将文件夹名保存到一个临时文件中，避免直接使用环境变量传递
          echo "$changed_folders" > changed_folders.txt

          # 将文件路径传递给后续步骤
          echo "changed_folders_file=changed_folders.txt" >> $GITHUB_ENV

      # Step 3: Create or update a release for the changed folders
      - name: Create or update a release for the changed folders
        if: env.changed_folders_file != ''  # 仅当有文件夹变更时才运行
        run: |
          # 从文件中读取更改的文件夹
          changed_folders=$(cat "${{ env.changed_folders_file }}")
          
          # 确保 changed_folders 不为空
          if [ -z "$changed_folders" ]; then
            echo "No folders to process. Exiting."
            exit 0
          fi

          for folder in $changed_folders; do
            # 检查文件夹是否存在
            if [ ! -d "$folder" ]; then
              echo "Folder $folder does not exist. Skipping."
              continue
            fi
            
            echo "Processing folder: $folder"
            
            folder_name=$(basename "$folder")

            # 打包文件夹为 ZIP 文件
            zip_file="${folder_name}.zip"
            zip -r "$zip_file" "$folder"

            # 检查是否已有同名 tag 的 release
            release_response=$(curl --request GET \
              --url "https://api.github.com/repos/${{ github.repository }}/releases/tags/$folder_name-release" \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}")

            # 检查返回的状态码
            release_id=$(echo "$release_response" | jq '.id')

            echo "request release_id $release_id"

            if [ "$release_id" == "null" ]; then
              # 如果没有 release，则创建新的 release
              release_response=$(curl --request POST \
                --url "https://api.github.com/repos/${{ github.repository }}/releases" \
                --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                --header "Content-Type: application/json" \
                --data '{
                  "tag_name": "'"$folder_name-release"'",
                  "target_commitish": "'"${{ github.sha }}"'",
                  "name": "'"$folder_name"'",
                  "draft": false,
                  "prerelease": false
                }')

              # 获取新的 release_id
              release_id=$(echo "$release_response" | jq '.id')
              echo "create release_id $release_id"
            else
              echo "Release already exists. Updating the release."
            fi

            # 获取 release 资产列表，检查是否已有同名资产
            assets=$(curl --request GET \
              --url "https://api.github.com/repos/${{ github.repository }}/releases/$release_id/assets" \
              --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}")

            # 查找与 zip 文件名匹配的资产
            asset_id=$(echo "$assets" | jq -r ".[] | select(.name == \"$zip_file\") | .id")

            echo "asset_id $asset_id"

            if [ -n "$asset_id" ]; then
              # 如果存在同名资产，更新该资产
              release_response=$(curl --request PATCH \
                --url "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id" \
                --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                --header "Content-Type: application/json" \
                --data '{
                  "name": "'"$zip_file"'",
                  "label": "Updated ZIP file for '"$folder_name"'"
                }')
            else
              # 如果没有同名资产，上传 ZIP 文件
              release_response=$(curl --request POST \
                --url "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=$zip_file" \
                --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                --header "Content-Type: application/zip" \
                --upload-file "$zip_file")
            fi
            echo "upload_response $release_response"
          done
        shell: bash